#!/bin/bash

if [ $# -eq 0 ]; then
    cd /home/kali/hacks/lin-priv-tools
    ls -la
    python -m http.server 80
else
    cd /home/kali/hacks/lin-priv-tools
    ls -la
    python -m http.server $1
fi